### PR TITLE
Add `check_*_within_dist` examples

### LINKED ISSUE #22: Document check_bytes_arrays_within_dist
I was looking into how to add something like this, and found that it's already there, but you have to look into the (admittedly short) source to find it. Please add a simple example to the docs on how to use it. Thanks!

### PR DESCRIPTION
**Pull request by mrecachinas**
Closes #22.

### CODE REVIEW

**Comment by RandomNameUser** [comment]
Hm, not sure this is correct. `check_bytes_arrays_within_dist` checks a bytes record against a whole _array_ of them and returns whether any of them have a shorter hamming distance than the threshold, which is very different from `check_hexstrings_within_dist`, which only checks one strings. That also motivated my other issue (#23), as the former can take a pretty long time.
Thanks!

**Comment by mrecachinas** [comment]
I'm not sure I fully understand the problem, are you suggesting there's an issue with the phrasing in

> Similarly, ``hexhamming`` supports byte strings via ``check_bytes_arrays_within_dist``, which has
the same API as ``check_hexstrings_within_dist``, except it expects a byte string.

If so, I'm happy to change the verbiage to "byte array", but just to make sure we're on the same page, below is how you would use both functions.

```python
check_hexstrings_within_dist("00000000", "0000000f", 3) # => False
```

```python
check_bytes_arrays_within_dist(b"\x00\x00\x00\x00", b"\x00\x00\x00\x0f", 3) # => False
```

It's true that `b"\x00\x00\x00\x00"` is equivalent to `[0, 0, 0, 0]` and `b"\x00\x00\x00\x0f"` is equivalent to `[0, 0, 0, 15]`.

**Comment by RandomNameUser** [comment]
Yes and no. If I understand the code correctly and looking at the test cases, the big difference is that you can call `check_bytes_arrays_within_dist` with an _array_ of elements and a single element to compare against all elements of the array, so essentially you can check whether your test element has a match less than distance bits in the big array. whereas `check_hexstrings_within_dist` only accepts arguments that have the same length and compares them.

**Comment by mrecachinas** [comment]
Ha, my bad! 🙇 You're absolutely right. I thought I wrote this function, but it was contributed a few years ago: https://github.com/mrecachinas/hexhamming/pull/10.

I'll update the wording accordingly tomorrow.

**Comment by mrecachinas** [comment]
@RandomNameUser check the latest to see if that's more accurate.

**Review by RandomNameUser — APPROVED** [review]
I would say commit it, even if it's not totally clear. 

I'm working on a PR with some other changes and I'll write a little more in the README. I'll try to put it up later today, so if you're thinking of making a new release please hold on that for a little bit.

Thanks!

**Pull request merged**
