### PR TITLE
Arm, sdist, musli, windows builds.

### PR DESCRIPTION
**Pull request by bigcat88**
- Moved version to separate file, to edit it in one place.
- Slightly changed setup.py
- In most functions changed return value from int to uint64_t.
- The same for input length, changed it to uint64_t.
- Added ARM implementation for hamming_distance_bytes__extra.
- Added to YML file building of `arm, sdist, musli, windows`.
- After publishing of wheels I will test them on M1(did not test cross building in cibuildwheel yet).

Note: 32 bit version fail tests, so did not added x86 build to Windows and i686 to linux.

#11 #12

### CODE REVIEW

**Comment by mrecachinas** [comment]
Ah shoot, this was linked to my previous PR. Sorry about that. Can you open a new PR?

**Comment by mrecachinas** [comment]
Let me know when this is good for me to review and merge.

**Comment by bigcat88** [comment]
@mrecachinas in last part of pull request reduce size of yml file by 50+ lines, make some adjustments.
Yes this is good.

**Comment by bigcat88** [comment]
@mrecachinas Now it is really final, nothing can be done to make yml smaller(only to rewrite building according to PEP 517, will do it in a month or two)

**Comment by mrecachinas** [comment]
LGTM

**Pull request merged**
