### PR TITLE
Additional changes to make github actions happy.

### PR DESCRIPTION
**Pull request by bigcat88**
1. Added `-s` parameter to pytest, to see output of tests.
2. In tests added this output: `print(f'Warning: Skipping {algorithm}, reason: {result}')` 
3. `set_algo` now checks if cpu can run those algorithm.

P.S.:
On GitHub MacOS `sysctl -a | grep machdep.cpu.features` reports that AVX is present(`avx1.0`) but `cpuid` reports that `avx2.0` is not. So now set_algo checks for cpu capabilities and tests for `extra` on MacOS are currently skipped. It's fine with this.

### CODE REVIEW

**Comment by mrecachinas** [comment]
@bigcat88 Please pull in the latest changes to master, which should enable CI to run on pull requests.

**Comment by bigcat88** [comment]
i saw that you added build for another archs, just to you to know, i didnt currently add code or test it on arm or anything else except x86, i will do that probably during two next weeks...
but if update for x86 will be published till monday, we will release update for our app that uses hexhamming, and get some comments from people about how it works.

p.s.: last `fedora` ships with python 3.10 :)

**Comment by mrecachinas** [comment]
Sounds good. FYI, I just published 2.2.0 to PyPI. Test it out. In the meantime, I'll test usings cibuildwheel.

**Comment by bigcat88** [comment]
@mrecachinas Can you please upload python 3.10 wheel? =)

**Comment by mrecachinas** [comment]
Done!

**Pull request merged**
