### PR TITLE
Cibuildwheel

### PR DESCRIPTION
**Pull request by mrecachinas**

### CODE REVIEW

**Comment by bigcat88** [comment]
@mrecachinas 
sorry for bothering you, but maybe is something with what can I help?
we want to publish a new release of our app, with support for this changes for arm cpu users..

**Comment by mrecachinas** [comment]
Once CI passes, I'll go ahead and merge.

**Comment by mrecachinas** [comment]
There's an issue with the same wheel being generated multiple times, which therefore errors on each subsequent `twine upload`. In any event, v2.2.1 is published to PyPI. Try it out and let me know if there are issues.

Thanks again for all your help!

**Comment by bigcat88** [comment]
@mrecachinas I am pretty sure that it is caused by missing flag `--skip-existing` in twine step and the same release version.
Like here: [twine upload](https://github.com/bigcat88/pillow_heif/blob/e31d0d899a16e23d334be8046849a0a469edccc3/.github/workflows/publish-pypi.yaml#L37)
I did not increment a version in pull request, was assuming that you will do that.
And there is missing alpine wheels, can you add them? (Imho, would be better to increase version and regenerate 2.3.0 for example)

**Comment by bigcat88** [comment]
@mrecachinas as you can see here: [wheels](https://github.com/bigcat88/hexhamming/suites/5249147367/artifacts/161715441) actions is ok.(I cloned your repo and commented publishing to test it)

**Pull request merged**
